### ISSUE TITLE
Create big wrapping function for all indicators

### ISSUE THREAD

**Issue by alexgenin** [fdschneider/spatial_warnings#22]
Create a function that will compute all the indicators and produce a summarizable/plottable object. 

```r 
# We need a catchy short name for that
all_indicators <- function(data, # `binary_matrix` object
                           indicators = list(variance = indicator_variance, psd = indicator_psd, ...), # list of functions
                           ?)

```

It should return an object of class `indicators` with the following structure: 

```r
list(variance = list(value = xx, ...), # OR variance = xx
     skewness = list(value = xx, ...), 
     psd = `psd object`, 
     ...) # Component names are taken from the list of functions above.
(class: c('spatial_indicators', 'list'))
```

Numerical indicators (e.g. variance, skewness, moran's I) should have a `value=` in their output list so they get recognized by the `summarize` function.

**Comment by alexgenin** [comment]
Added a first version named `indicator_all` (name suggestions welcome !) in 6f6b1f14e6b3db90b1306550bfff2e9d0a6db088

**Comment by fdschneider** [comment]
I would call this function just `indicators()` or `spatialwarnings()` since the argument `indicators = list()` can be used to specify which indicators to run and store in the output object. Thus, all the individual indicator functions could be hidden functions that can be called directly using the syntax `spatialwarnings::cumpsd()`. The end user would only rarely call them directly. 

This also requires the documentation/man pages to be well linked to each other. 

Very convenient: Adding user specified functions to the argument would run those on the input object as well  and drop the output in the `indicators` object.

Two issues with this structure: 
1. how do we pass on arguments to the individual indicator functions? 
2. If the input is a lists of binary matrices, the output should be a list of `indicator` objects. Then, how do we extract a single output or information for each input object? e.g. if we would want to know the exponent of the cumulative patch size distribution function only, how do we obtain a vector of these? This requires a specific call like  `sapply(L, function(x) coefficients(x$cumpsd$fit)$alpha )` . Can we provide a simple wrapper for extracting information from the list object into a vector or table?

**Comment by alexgenin** [comment]
I think `spatialwarnings()` is simple and good indeed, if we all agree on that, please anybody feel free to change the name. I would still export the individual indicator functions though, if people want to tinker with "raw" indicator values (e.g. when reusing them in other kinds of data analyses).

For the other points : 

 1. Right now arguments are passable as a named list, for instance passing `replicates=500` to `indicator_variance` can be done this way: 

```r
all_indicators(indicators = list(variance = indicator_variance),
               args =       list(variance = list(replicates = 500))
```
A bit cumbersome though. 

 2. Maybe a good way to simplify all of this data extraction is following the g/lm's way of doing things. Basically we create a `summary.spatial_indicators` that summarizes all the data into a shallow (1-level list) of tables and assign a `summary.spatial_indicators` class. A print method is then defined for that class, that does all the pretty-printing work. This way people can extract already-summarized data from the summary object (I hope I'm clear ?).

Things would behave this way :
```r
> summary(<spatial_indicator_object>)
<prints pretty table >
> a <- summary(<spatial_indicator_object>)
# (not printed, but shows the structure of a)
list(numeric_indicators = <data.frame with columns value/pval/etc.>, #  see #23
     psdfit = <data.frame with columns model/fit/AIC/test/...>, # (== summary(<psdfit object>))
     fractal_geometry = <////>) # (== summary(<fracgeo object>))

# Extract the fit alpha scores :
> a$psdfit[ ,'alpha']
[1] ...
# Print the pretty table
> print(a)
<prints pretty table >
```

> This also requires the documentation/man pages to be well linked to each other. 

If I remember correctly, there is a @family roxygen tag to show that functions belong to the same family (they will appear together in the *See Also* section)

**Comment by guttal** [comment]
I don't exactly know how these wrapper functions work, but I am not sure if we should "Create a function that will compute all the indicators and produce a summarizable/plottable object." 

It may be better if the spatialwarning() itself has several functions that does smaller tasks. For example, if you look at (temporal) earlywarnings package, it does not calculate everything that can be calculated for a time series. You have different functions for different analyses. Look at this screen shot for list of all functions within the earlywarnings package. If you agree, we should think of and come with simpler functions within the package. 

![screen shot 2015-10-08 at 9 03 26 pm](https://cloud.githubusercontent.com/assets/12860723/10371247/0c678ef8-6e00-11e5-95b2-5dc313b37fee.png)

Likewise, we could have generic_spatial_warnings that calculates numerical indicators like mean, variance, skewness, moranI, etc could be one function within the package. Then patch-size-distribution could be the other. Correlation and spectral functions could be combined (or separated). Separating these will also help a lot because correlation function or patch sizes, for example, could take a very long time obtain. If all are done in one go, it may be very slow for big spatial data.  

Let me know your thoughts.

**Comment by guttal** [comment]
I just realised there is some overlap with issue #19

**Comment by guttal** [comment]
By the way, if I am raising issues which you guys have already thought about and discussed here, just let me know. I could easily have missed them since I haven't followed all discussions closely.

**Comment by alexgenin** [comment]
Yes ! This is right on the spot. 

I don't have much time now for the package, but I spent some time working on the code this afternoon and I am reaching a similar conclusion. It looks and feels artificial to combine for instance a patch-size-distribution fitting workflow (what is the most adequate distribution ? how does it look like ? does the best model change over some replicates ?) with a "generic indicator" workflow (what is the mean/variance/etc ? is it statistically higher than average ? where is the value in a null distribution ?). Both these two examples require different graphs and different diagnostic tools.

Due to this discrepancies between all workflows, there is some (manageable) complexity building up as we try to summarize/plot/etc (does it makes sense producing a single plot for a patch size distribution and a powerspectrum at the same time ?). However, it would be nice to have a single entry point for a new user to do "warning signal analyses" (maybe outside of actual interaction with R).

I now think that it makes more sense having "tasks" like in the `earlywarnings` package. However, I don't know where each indicator should go (Kéfi et al.2014, Fig. 2 is definitely a starting point).

I'm commiting my draft code from today but it is of course very likely to change.

**Comment by guttal** [comment]
Sure, I understand your time constraints. There is no strict deadline on this, and we work when at leisure.

**Comment by alexgenin** [comment]
Obsolete now.
