### ISSUE TITLE
High-resolution results

### ISSUE THREAD

**Issue by alexgenin** [fdschneider/spatial_warnings#34]
The model results are starting to arrive ! 
 
 - [x] [Grazing model](http://alex.lecairn.org/files/result_grazing_processed.rda) (~220 MB, ~3GB in memory)
 - [X] [Musselbed model](http://alex.lecairn.org/files/result_musselbed_processed.rda)
 - [x] [Forestgap model](http://alex.lecairn.org/files/result_forestgap_processed.rda) (~88MB)

As usual these files contain two variables: upper_branch and lower_branch. Both are lists of three components : 

1. DatBif
2. snaps
3. time_series (new!) containing the full time series of global and local cover

access them with `upper_branch[[1]]` (or 2 or 3)

**Comment by ssumithra** [comment]
Hi all,


I've fit the patch size distributions for the grazing model (it should
hopefully have found its way into your drafts folders as a folder called
'PSDs'). We have an issue here - right now the qualitative trends in patch
size distribution as the system approaches transition, are the same for all
values of the spatial stressor - i.e, even for the g=0 case (that is when
flo's model converged to sonia's model), a power law patch size
distribution is observed near the transition (see GrazingPSD_g0m0.208.jpg).
This could be because of two reasons -
1. The values chosen for the other paramater values (b, f) in the
simulation are such that the system undergoes a large catastrophic
transition irrespective of 'g'.
2. The resolution is still not sufficient to capture the shifting trends
near the transitions. This would mean we are missing the entire regime over
which increasing truncation in power law occurs.

I don't think the problem is point 1 because I see that the simulation has
been run for an 'f' value of  0.9 and b value of 0.5, for which I don't
think Sonia's model shows a discontinuous transition, but I could be wrong
about this.

Regards,
Sumithra

**Comment by SabihaMajumder** [comment]
Hi Sumithra,

You are right. Even with g=0 in Flo's model, we get a discontinuous
transition with a high jump. This could entirely be because of the lower
resolution of the simulations.
[image: Inline image 1]

**Comment by alexgenin** [comment]
Just added the results for forestgap model.

**Comment by alexgenin** [comment]
Added musselbed for completeness.
